### ISSUE TITLE
Build suggestions

### ISSUE THREAD

**Issue by ryanmkurtz** [mandiant/Ghidrathon#1]
I just installed Ghidrathon-1.0.0 and I ran into 2 very minor installation issues that were trivial to correct, but could potentially make the experience a bit more streamlined if addressed:

1. By default on Ubuntu 22.04, `python` is not on the path but `python3` is.  Perhaps you could test for both (probably starting with `python3` before failing.
2. Also by default, pip was not installed.  The error from Gradle didn't convey this...I had to run the `python3 -m pip install jep` command manually to figure out what was going on.  Perhaps that error messages can be relayed by Gradle somehow.

**Comment by mike-hunhoff** [comment]
thank you for the feedback! we will get these changes made to help improve the installation for users moving forward.
