### ISSUE TITLE
ghidra exits abnormally？Is it a bug of Ghidrathon Or Jep?

### ISSUE THREAD

**Issue by Vang3lis** [mandiant/Ghidrathon#14]
Here is the log.

[hs_err_pid121091.log](https://github.com/mandiant/Ghidrathon/files/9895454/hs_err_pid121091.log)

**Comment by IdanH101** [comment]
Same thing happened to me when I ran my python script twice - ghidra crashed.
Maybe it relates to issue #7 ?

**Comment by IdanH101** [comment]
@Vang3lis why did you close it? The problem still exists

**Comment by Vang3lis** [comment]
Sorry, I close this issue just because the issue https://github.com/mandiant/Ghidrathon/issues/7 you metioned has answer my question. I will reopen it.

**Comment by mike-hunhoff** [comment]
Thank you for the report @Vang3lis . Can you please provide additional information including:

- Ghidra version
- Python version
- Operating system
- Does the crash occur each time? Or is it nondeterministic?
- I gather from the attached log file this occurred when executing a script name `ghidrathon_example.py`. Is this the unmodified script shipped with Ghidrathon? If not and if possible, can you provide the referenced script?

@IdanH101 if possible can you also please provide provide the additional information requested above?

**Comment by Vang3lis** [comment]
Ghidra version: 10.1.2 OR 10.1.5 both can trigger.
Python version: 3.8.10 (I use the local python env)
Operating system: Ubuntu20.04 in VMware

Nondeterministic and it crashes when the script runs more than once. I do some modifications on this script. Here is the script.
[ghidrathon_example.zip](https://github.com/mandiant/Ghidrathon/files/9906312/ghidrathon_example.zip)

**Comment by IdanH101** [comment]
Ghidra version: 10.1.2
Python version: 3.6.5
O.S.: Windows 10

Crashes everytime I run any python script more than once.

**Comment by IdanH101** [comment]
> Ghidra version: 10.1.2 Python version: 3.6.5 O.S.: Windows 10
> 
> Crashes everytime I run any python script more than once.

I was wrong. I checked many scripts, but it just accured to me they all used numpy with multiarray!
The example script actually works great.

Further investigation lead me to this thread:
https://github.com/numpy/numpy/issues/19149

Is it possible that Ghidrathon have a problem with it for the reasons specified in that thread? Is there a work around?

**Comment by mike-hunhoff** [comment]
> Ghidra version: 10.1.2 OR 10.1.5 both can trigger. Python version: 3.8.10 (I use the local python env) Operating system: Ubuntu20.04 in VMware
> 
> Nondeterministic and it crashes when the script runs more than once. I do some modifications on this script. Here is the script. [ghidrathon_example.zip](https://github.com/mandiant/Ghidrathon/files/9906312/ghidrathon_example.zip)

@Vang3lis I had to modify the script that you attached to execute what I believe to be the intended entry method `_analyze`. Additionally, I had to comment out some lines to avoid a "method not found" exception. Following this I was able to execute your script but I could not re-create the issue. Can you please verify that you attached the correct script? Or ensure the attached script fully executes as intended in case the issue lies in the commented lines (65-69).

**Comment by mike-hunhoff** [comment]
> > Ghidra version: 10.1.2 Python version: 3.6.5 O.S.: Windows 10
> > Crashes everytime I run any python script more than once.
> 
> I was wrong. I checked many scripts, but it just accured to me they all used numpy with multiarray! The example script actually works great.
> 
> Further investigation lead me to this thread: [numpy/numpy#19149](https://github.com/numpy/numpy/issues/19149)
> 
> Is it possible that Ghidrathon have a problem with it for the reasons specified in that thread? Is there a work around?

@IdanH101 thank you for taking a second look. This issue appears to be caused by Ghidrathon's use of Jep's SubInterpreter versus Jep's SharedInterpreter (see Jep discussion [here](https://github.com/ninia/jep/wiki/Numpy-Usage#numpy-gotchas)). TLDR; numpy does not work with sub-interpreters resulting in the crashes you are experiencing. For now, numpy usage should be avoided until we can find a configuration that works for Ghidrathon. I'll open a separate issue to track progress. If you could provide an example script that uses numpy resulting in a crash that would certainly help.

**Comment by Vang3lis** [comment]
> > Ghidra version: 10.1.2 OR 10.1.5 both can trigger. Python version: 3.8.10 (I use the local python env) Operating system: Ubuntu20.04 in VMware
> > Nondeterministic and it crashes when the script runs more than once. I do some modifications on this script. Here is the script. [ghidrathon_example.zip](https://github.com/mandiant/Ghidrathon/files/9906312/ghidrathon_example.zip)
> 
> @Vang3lis I had to modify the script that you attached to execute what I believe to be the intended entry method `_analyze`. Additionally, I had to comment out some lines to avoid a "method not found" exception. Following this I was able to execute your script but I could not re-create the issue. Can you please verify that you attached the correct script? Or ensure the attached script fully executes as intended in case the issue lies in the commented lines (65-69).

Sorry, when I attached the script, I have modified some lines which are not related in my thought. I removed the line "import angr" and lines 65-69 should be commented.
