### ISSUE TITLE
add ARM support

### ISSUE THREAD

**Issue by nnothstine** [mandiant/Ghidrathon#27]
Thanks for this project! I am trying to deploy this in a Docker container (linux+arm64) without access to a GUI to turn on the extension, and have been debugging trying to find out why it doesn't seem to be loading after I clone it.

Ghidra's documentation [here](https://ghidra-sre.org/InstallationGuide.html#Extensions) seems to indicate that I should be able to simply clone this into the Ghidra extensions directory, so given a local installation path of `/home/nonroot/ghidra`, I would expect that to be `/home/nonroot/ghidra/Ghidra/Extensions`. The extension is unzipped and at `/home/nonroot/ghidra/Ghidra/Extensions/Ghidrathon-2.0.0`, and I've made sure to buildNatives, so I'd think I'd be good to go from there.

Still pretty new, so it's likely there's something I'm missing here. Attempting to run a headless analysis seems to be unable to parse the example script as Python 3, though:

```
INFO  SCRIPT: /home/nonroot/ghidra/Ghidra/Extensions/Ghidrathon-2.0.0/ghidra_scripts/ghidrathon_example.py (HeadlessAnalyzer)
  File "/home/nonroot/ghidra/Ghidra/Extensions/Ghidrathon-2.0.0/ghidra_scripts/ghidrathon_example.py", line 30
    f"Function {func.getName()} @ {hex(func.getEntryPoint().getOffset())}: {block_count} blocks, {insn_count} instructions"
    ^
SyntaxError: no viable alternative at input '"Function {func.getName()} @ {hex(func.getEntryPoint().getOffset())}: {block_count} blocks, {insn_count} instructions"'
```

Please let me know what context would be helpful here, if any.

**Comment by mike-hunhoff** [comment]
Hi @nnothstine - I successfully installed Ghidrathon 2.0 for Ghidra 10.2.2 by extracting the extension directly to `<ghidra_install_dir>\Ghidra\Extensions`. Ghidrathon hasn't been tested on arm64 (we don't have an arm64 environment readily available) so it's likely Ghidrathon is failing to execute properly. The error you are seeing is the result of Ghidra attempting to execute a Python 3 script using Jython (the default behavior if Ghidrathon fails to load).

It looks like you built the arm64 Jep native binary required for Ghidrathon to execute? Where did you place it under Ghidrathon's `os` folder? Ghidra expects Linux arm64 binaries to be placed in a folder named `linux_arm_64` under an eactension's `os` directory (https://github.com/NationalSecurityAgency/ghidra/blob/c51183f1a262c80d45aac48d4f3343c67b6bd41a/GPL/nativePlatforms.gradle#L21-L28).

**Comment by rchtsang** [comment]
I was able to get it working in the GUI after renaming `linux_x86_64` to `linux_arm_64`. I have not tried analyzeHeadless. My Dockerfile can be found [here](https://github.com/rchtsang/docker-ghidrathon/blob/main/README.md)

I'm on Mac M1 Pro (OSX 13.0.1) using Ghidra v10.2.2, cloning directly from the Ghidrathon repo.

**Comment by mike-hunhoff** [comment]
@rchtsang thank you for the update! I'm going to edit the name this issue to focus on adding ARM support - I hope this is something we can get working in #4. I've already opened #29 to track updating the plugin README to include direct extract to `...\Ghidra\Extensions`.

**Comment by mike-hunhoff** [comment]
Fixed in https://github.com/mandiant/Ghidrathon/commit/32f3969e09a5d29197cabbc28d93dc9c572d7e45 - please reopen if you continue to have issues after this is released.
