### ISSUE TITLE
Could not build extension for Ghidra 10.2.2

### ISSUE THREAD

**Issue by as0ni** [mandiant/Ghidrathon#28]
Having an issue building for 10.2.2. 

I did notice this similar closed ticket: https://github.com/mandiant/Ghidrathon/issues/18. However, I tried the same build command below for 10.2.1 and 10.2 and received the same error in both cases. Am I missing something? 

Thanks for any help.

```
C:\Tools\Ghidrathon\Ghidrathon-2.0.0>gradle -PGHIDRA_INSTALL_DIR="C:\Program Files (x86)\ghidra_10.2.2_PUBLIC"

> Task :installJep
Requirement already satisfied: jep in c:\users\analyst\appdata\local\programs\python\python39\lib\site-packages (4.0.3)

> Task :copyJepNativeBinaries
2023-01-06 17:37:51,049 INFO     Searching for Jep Python module directory
2023-01-06 17:37:51,049 INFO     Found Jep Python module directory at C:\Users\analyst\AppData\Local\Programs\Python\Python39\lib\site-packages\jep
2023-01-06 17:37:51,049 INFO     Copying jep.dll and C:\Users\analyst\AppData\Local\Programs\Python\Python39\lib\site-packages\jep\jep-4.0.3.jar to extension folders
2023-01-06 17:37:51,049 INFO     Done

> Task :compileJava FAILED
C:\Tools\Ghidrathon\Ghidrathon-2.0.0\src\main\java\ghidrathon\GhidrathonScriptProvider.java:19: error: cannot find symbol
import ghidra.app.script.GhidraScriptLoadException;
                        ^
  symbol:   class GhidraScriptLoadException
  location: package ghidra.app.script
C:\Tools\Ghidrathon\Ghidrathon-2.0.0\src\main\java\ghidrathon\GhidrathonScriptProvider.java:39: error: cannot find symbol
                        throws GhidraScriptLoadException {
                               ^
  symbol:   class GhidraScriptLoadException
  location: class GhidrathonScriptProvider
C:\Tools\Ghidrathon\Ghidrathon-2.0.0\src\main\java\ghidrathon\GhidrathonPlugin.java:53: error: no suitable constructor found for ProgramPlugin(PluginTool)
                super(tool);
                ^
    constructor ProgramPlugin.ProgramPlugin(PluginTool,boolean,boolean,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor ProgramPlugin.ProgramPlugin(PluginTool,boolean,boolean) is not applicable
      (actual and formal argument lists differ in length)
C:\Tools\Ghidrathon\Ghidrathon-2.0.0\src\main\java\ghidrathon\GhidrathonScriptProvider.java:48: error: cannot find symbol
                        throw new GhidraScriptLoadException("Unable to instantiate: " + e.getMessage(), e);
                                  ^
  symbol:   class GhidraScriptLoadException
  location: class GhidrathonScriptProvider
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
3 actionable tasks: 3 executed
```

**Comment by mike-hunhoff** [comment]
Hi @as0ni - I just worked through a successful install of Ghidrathon 2.0 for Ghidra 10.2.2 on Ubuntu with Python 3.8.10. Can you provide the following for your install?

- OS architecture
- OS version
- Ghidra version
- Java version
- Python version
- Jep version
- Ghidrathon version

**Comment by as0ni** [comment]
Sure thing. 

- OS architecture: 64-bit
- OS version: Windows 10 Enterprise 21H1
- Ghidra version: 10.2.2
- Java version: openjdk version "17.0.5" 2022-10-18
- Python version: Python 3.9.7
- Jep version: 4.0.3
- Ghidrathon version: 2.0

Thanks for looking into this @mike-hunhoff!

**Comment by as0ni** [comment]
@mike-hunhoff FWIW I did use gradle to create the latest dev release of Ghidra (ghidra_10.3_DEV) on my system and tried installing Ghidrathon. Unfortunately I got the same error. 

I author a SANS RE class (https://sans.org/for710) and would love to include Ghidra 10.2.2 and Ghidrathon 2.0 in an upcoming revision if possible. 

Appreciate the help, thank you.

**Comment by mike-hunhoff** [comment]
@as0ni I forgot to ask what version of gradle are you using?

**Comment by as0ni** [comment]
@mike-hunhoff Gradle 7.5.1

**Comment by mike-hunhoff** [comment]
Thank you @as0ni . Out of curiosity do you have an environment variable named `GHIDRA_INSTALL_DIR` set? I'm wondering if the following code from Ghidrathon's gradle script is causing gradle to reference an older Ghidra install directory during the build: https://github.com/mandiant/Ghidrathon/blob/83515552de0b8694a0a1c8b26b9a8303f41046be/build.gradle#L61-L66

**Comment by as0ni** [comment]
@mike-hunhoff, argh, that was it! Thank you so much!

**Comment by mike-hunhoff** [comment]
No problem @as0ni the build script should make it obvious which Ghidra install is being used and I created #31 to help eliminate this confusion in the future. I am going to close this issue as resolved. Please reopen or create a new issue if needed. Thank you!
