### ISSUE TITLE
Virtualenv under Windows

### ISSUE THREAD

**Issue by larsborn** [mandiant/Ghidrathon#3]
I followed the installation instructions from the readme and would like to use a virtual environment. When activating that venv (with `/path/to/venv/Scripts/activate.bat`), and executing `ghidraRun.bat`, Ghidra shows the following exception when I try to open the Ghidrathon window:

```
java.lang.RuntimeException: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'jep'
	at ghidrathon.interpreter.GhidrathonInterpreter.get(GhidrathonInterpreter.java:215)
	at ghidrathon.GhidrathonConsoleInputThread.run(GhidrathonConsoleInputThread.java:59)
Caused by: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'jep'
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:312)
	at jep.Jep.configureInterpreter(Jep.java:179)
	at jep.Jep.<init>(Jep.java:159)
	at jep.Jep.<init>(Jep.java:128)
	at jep.SubInterpreter.<init>(SubInterpreter.java:63)
	at ghidrathon.interpreter.GhidrathonInterpreter.<init>(GhidrathonInterpreter.java:74)
	at ghidrathon.interpreter.GhidrathonInterpreter.get(GhidrathonInterpreter.java:210)
	... 1 more
```

Operating System: Windows 10
Java Version: OpenJDK 11.0.16
Ghidra Version: 10.1.5
Python Version: 3.9.1
Jep Version: 4.0.3

If I don't use a venv but just install `jep` into the system-wide Python installation, Ghidrathon works as expected. So I assume it has something to do with `ghidraRun.bat` not correctly passing the environment variables from the currently active venv?

**Comment by mike-hunhoff** [comment]
@larsborn thank you for reporting - I am able to recreate this in my environment. We will need to take a closer look at the execution chain spawned by `ghidraRun` on Windows to see if we can identify where the `virutalenv` is lost.

**Comment by williballenthin** [comment]
according to here: https://stackoverflow.com/a/73231788
activating a virtual environment just updates the PATH environment variable to prefer the python.exe (and other executables) in the virtualenv. it sets $VIRTUAL_ENV, but this *typically* isnt used.

the sense i get from here: https://github.com/ninia/jep/issues/76
is that JEP doesn't directly invoke python.exe, but uses the an embedded python interpreter found in jep.dll. this isn't influenced by $PATH, so activating the virtualenv doesn't change where JEP finds python; this is only configured via PyConfig.setPythonHome() and MainInterpreter.setJepLibraryPath.

therefore, i think we should update Ghidrathon to check for $VIRTUAL_ENV being set, and if so, use that to update PyConfig.setPythonHome().

**Comment by mike-hunhoff** [comment]
Fixed in https://github.com/mandiant/Ghidrathon/commit/32f3969e09a5d29197cabbc28d93dc9c572d7e45 - please reopen if you continue to have issues after this is released.

**Comment by larsborn** [comment]
Hey @mike-hunhoff, 
awesome news and thanks a lot for figuring this one out!! I couldn't wait so instead of waiting for a new Ghidrathon release (or would that even be your recommendation?), I tried to build a new one myself with gradle (heads up: I've never used gradle before).

```
gradle -Dorg.gradle.java.home="C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot" -PGHIDRA_INSTALL_DIR="C:\Program Files\ghidra_11.0_PUBLIC\"
```

(I needed to specify the JDK explicitly because I have multiple Java versions installed).

This leads to a ZIP file in the `dist` directory which I promptly installed as a Ghidra extension. One observation right off the bat was that the "Ghidrathon" entry doesn't seem to appear in the Windows menu.

When I then create a "Python 3" script (the entry does exist and was not there before, so installing the extension did _something). and try to execute the script, the Ghidra window just disappears (I assume it crashed).

Could you give me some pointers what I can do now to debug? Or should I rather wait for a new release?

Again: thanks for creating this extension. I'm really looking forward to using it because I think it'll fundamentally change the amount of scripts folks write for Ghidra (Java is just a pretty high barrier of entry).

**Comment by mike-hunhoff** [comment]
@larsborn thank you for your feedback and excitement! Let's see if we can track this down by getting some additional information.

Did you follow the build requirements and steps listed [here](https://github.com/mandiant/Ghidrathon/blob/main/doc/building.md)?
Did you follow the install requirements and steps listed [here](https://github.com/mandiant/Ghidrathon?tab=readme-ov-file#installing-ghidrathon)?

Can you provide the content your Ghidra install's `application.log` file? (e.g. `<home_directory>\.ghidra\.ghidra_11.0_PUBLIC\application.log`)

**Comment by mike-hunhoff** [comment]
@larsborn check out [today's release](https://github.com/mandiant/Ghidrathon/releases/tag/v4.0.0-rc1). This should fix your issue here but please reopen this issue if it does not.
