### ISSUE TITLE
add MacOS support

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/Ghidrathon#34]
see #4

- [x] x86_64
- [ ] M1 ARM

**Comment by Cnly** [comment]
For 1.0.0 and 2.0.0, I've been using Ghidrathon on mac with no problems running a bunch of my own scripts. All it takes is a 10-line patch to let Ghidrathon find `jep.cpython-310-darwin.so` (for other python versions 310 may need to change) instead of `libjep.so`. I'm not sure whether #4 is larger because it handles lots of special cases? But if desired, maybe I can convert that patch to a basic PR and #4 can continue its extended work and be merged later.

**Comment by mike-hunhoff** [comment]
@Cnly this sounds great and much appreciated! Yes please open a PR w/ the aforementioned changes independent of the changes being worked in #4. Ideally we'd handle all Python versions supported by Ghidrathon. Would you be able to test another Python version or two to see how the filename is affected? Unfortunately we don't have a Mac environment on our end for testing.

**Comment by rchtsang** [comment]
I'm on M1 ARM. I don't think the x86 solution works for me but here's what i've been doing:

- Create a virtual environment with conda. activate it
- install python 3.10 with pip.
- pip install jep
- look in the environment's site-packages for jep's library
    - it should be libjep.jnilib
- overwrite the `configure_jep_native_binaries.py` to use libjep.jnilib and copy into a folder named `mac_arm_64` instead of `linux_x86_64`
- build with gradle per usual instructions (with venv activated)
- after the build is done, extract the resulting extension .zip file to the Extensions/Ghidra/Extensions folder in the Ghidra home directory
- go into the extracted extension's folder. find the `mac_arm_64` folder and rename `libjep.jnilib` to `jep.dll`
- follow rest of install instructions

haven't had time to automate all of this but it should be straightforward if anyone needs a quick and dirty method.

**Comment by cyberkaida** [comment]
I'm on M1 ARM on Ventura, I just did the following and Ghidrathon worked out of the box for me:

```diff
diff --git a/build.gradle b/build.gradle
index 59b952f..4cc1ae4 100644
--- a/build.gradle
+++ b/build.gradle
@@ -29,7 +29,7 @@ if (project.hasProperty("PYTHON_BIN")) {
 	pythonBin = project.getProperty("PYTHON_BIN")
 }
 else {
-	pythonBin = "python"
+	pythonBin = "python3"
 }
 
 // we need to install Jep; this requires C++ build tools on Windows (see README); we need to define
@@ -73,4 +73,4 @@ if (ghidraInstallDir) {
 else {
     throw new GradleException("GHIDRA_INSTALL_DIR is not defined!")
 }
-//----------------------END "DO NOT MODIFY" SECTION-------------------------------
\ No newline at end of file
+//----------------------END "DO NOT MODIFY" SECTION-------------------------------
```

Then I built with Gradle and Ghidra 10.3 and Ghidrathon worked out of the box!

**Comment by austinc3030** [comment]
> I'm on M1 ARM on Ventura, I just did the following and Ghidrathon worked out of the box for me:
> 
> ```diff
> diff --git a/build.gradle b/build.gradle
> index 59b952f..4cc1ae4 100644
> --- a/build.gradle
> +++ b/build.gradle
> @@ -29,7 +29,7 @@ if (project.hasProperty("PYTHON_BIN")) {
>  	pythonBin = project.getProperty("PYTHON_BIN")
>  }
>  else {
> -	pythonBin = "python"
> +	pythonBin = "python3"
>  }
>  
>  // we need to install Jep; this requires C++ build tools on Windows (see README); we need to define
> @@ -73,4 +73,4 @@ if (ghidraInstallDir) {
>  else {
>      throw new GradleException("GHIDRA_INSTALL_DIR is not defined!")
>  }
> -//----------------------END "DO NOT MODIFY" SECTION-------------------------------
> \ No newline at end of file
> +//----------------------END "DO NOT MODIFY" SECTION-------------------------------
> ```
> 
> Then I built with Gradle and Ghidra 10.3 and Ghidrathon worked out of the box!

Did this work on an m1 mac though? I am on an m1 mac mini and discovered this change on my own, which allowed it to build successfully. I can get it installed/added into ghidra, but when launching it, it pukes complaining about architecture types. 

```
/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so: dlopen(/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so, 0x0001): tried: '/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so' (no such file), '/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
java.lang.UnsatisfiedLinkError: /Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so: dlopen(/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so, 0x0001): tried: '/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so' (no such file), '/Users/austinc/.ghidra/.ghidra_10.3_PUBLIC/Extensions/Ghidrathon/os/mac_arm_64/libjep.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at jep.MainInterpreter.initialize(MainInterpreter.java:126)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:133)
	at jep.Jep.<init>(Jep.java:128)
	at jep.SubInterpreter.<init>(SubInterpreter.java:63)
	at ghidrathon.interpreter.GhidrathonInterpreter.<init>(GhidrathonInterpreter.java:124)
	at ghidrathon.interpreter.GhidrathonInterpreter.get(GhidrathonInterpreter.java:264)
	at ghidrathon.GhidrathonConsoleInputThread.run(GhidrathonConsoleInputThread.java:62)

---------------------------------------------------
Build Date: 2023-May-10 1508 EDT
Ghidra Version: 10.3
Java Home: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
JVM Version: Eclipse Adoptium 17.0.7
OS: Mac OS X 13.0.1 aarch64
```

**Comment by williballenthin** [comment]
we need to be careful in this thread about which architecture is being used. macOS has (usually) nice x86 compatibility via Rosetta, so it's easy to mix up whether we're loading java/python/ghidra in x86 or arm mode.

for example, in @austinc3030's traceback above, we can see:

```
.../os/mac_arm_64/libjep.so: dlopen(.../os/mac_arm_64/libjep.so, 0x0001): 
  tried: '.../os/mac_arm_64/libjep.so' 
  (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), 
```

which suggests that the jep.dll is built for x86 (so maybe python3 x86 was invoked to build jep.dll) but ghidra and java are running on arm64.

unfortunately, im still pretty new to macOS so i dont have the specific commands needed to confirm the architectures being used (but i suspect `file /path/to/executable` will show it).

i'll try to reproduce as well and report back.

**Comment by hiro4bbh** [comment]
I found that rpath is not set in `libjep.so` (at least my environment), so after I fix to set rpath, it worked on my environment (M2 MBA 2022, Ventura 13.5).

```
% otool -L $HOME/.ghidra/.ghidra_10.3.2_PUBLIC/Extensions/Ghidrathon-2.2.0/os/mac_x86_64/libjep.so
$HOME/.ghidra/.ghidra_10.3.2_PUBLIC/Extensions/Ghidrathon-2.2.0/os/mac_x86_64/libjep.so (architecture x86_64):
        @rpath/Python3.framework/Versions/3.9/Python3 (compatibility version 3.9.0, current version 3.9.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
$HOME/.ghidra/.ghidra_10.3.2_PUBLIC/Extensions/Ghidrathon-2.2.0/os/mac_x86_64/libjep.so (architecture arm64):
        @rpath/Python3.framework/Versions/3.9/Python3 (compatibility version 3.9.0, current version 3.9.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
% find / -name 'Python3'
...
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Python3
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Python3
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Python3
...
% install_name_tool -add_rpath /System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Library/Frameworks/ $HOME/.ghidra/.ghidra_10.3.2_PUBLIC/Extensions/Ghidrathon-2.2.0/os/mac_x86_64/libjep.so
% otool -L $HOME/.ghidra/.ghidra_10.3.2_PUBLIC/Extensions/Ghidrathon-2.2.0/os/mac_x86_64/libjep.so
$HOME/.ghidra/.ghidra_10.3.2_PUBLIC/Extensions/Ghidrathon-2.2.0/os/mac_x86_64/libjep.so (architecture x86_64):
        @rpath/Python3.framework/Versions/3.9/Python3 (compatibility version 3.9.0, current version 3.9.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
$HOME/.ghidra/.ghidra_10.3.2_PUBLIC/Extensions/Ghidrathon-2.2.0/os/mac_x86_64/libjep.so (architecture arm64):
        @rpath/Python3.framework/Versions/3.9/Python3 (compatibility version 3.9.0, current version 3.9.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
```

**Comment by Cnly** [comment]
I'm now on Apple Silicon and the latest commit 7489831 already works for me out of the box. My gradle command is

```sh
gradle -PGHIDRA_INSTALL_DIR=/opt/homebrew/Caskroom/ghidra/10.3.3-20230829/ghidra_10.3.3_PUBLIC -PPYTHON_BIN=/opt/homebrew/bin/python3
```

and it seems that `libjep.so` is also correctly built:

```sh
$ file os/mac_x86_64/libjep.so
os/mac_x86_64/libjep.so: Mach-O 64-bit bundle arm64
```

**Comment by hiro4bbh** [comment]
Oh..., on my environment, your approach did not work.

```
% gradle -PGHIDRA_INSTALL_DIR="${GHIDRA_PATH}" -PPYTHON_BIN="$(which python3)"
% file $HOME/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so
/Users/XXX/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64]
/Users/XXX/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so (for architecture x86_64):   Mach-O 64-bit bundle x86_64
/Users/XXX/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so (for architecture arm64):    Mach-O 64-bit bundle arm64
```

```
Can't load library: /Users/XXX/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so
java.lang.UnsatisfiedLinkError: Can't load library: /Users/XXX/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at jep.MainInterpreter.initialize(MainInterpreter.java:126)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:133)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:60)
	at ghidrathon.interpreter.GhidrathonInterpreter.<init>(GhidrathonInterpreter.java:72)
	at ghidrathon.interpreter.GhidrathonInterpreter.get(GhidrathonInterpreter.java:232)
	at ghidrathon.GhidrathonConsoleInputThread.run(GhidrathonConsoleInputThread.java:66)

---------------------------------------------------
Build Date: 2023-Aug-29 1442 EDT
Ghidra Version: 10.3.3
Java Home: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
JVM Version: Oracle Corporation 17.0.8
OS: Mac OS X 13.5.2 aarch64
```

After applying my rpath patching, Ghidrathon 3.0.1 works expectedly.

**Comment by mike-hunhoff** [comment]
This should be addressed in https://github.com/mandiant/Ghidrathon/commit/32f3969e09a5d29197cabbc28d93dc9c572d7e45 - please reopen if you continue to have issues after this is released.
