### ISSUE TITLE
Headless Ghidrathon extension installation

### ISSUE THREAD

**Issue by colton-gabertan** [mandiant/Ghidrathon#47]
After building the extension, Ghidra's documentation tells us to unzip it in the `$GHIDRA_INSTALL_DIR/Extensions` diretory; however, putting it in this directory only gives it visibility to perform the actual installation via the gui. To avoid having to configure the extension in the gui, we must extract the zip to `~/.ghidra/.ghidra_<version>/Extensions`

>note: The `Extensions` folder will not be present in the hidden directories (.ghidra*), so we must manually create it before/ during the extraction process

Invocation of the headlessAnalyzer should now be using Ghidrathon to process python scripts instead of the default Jython plugin.

**Comment by williballenthin** [comment]
perhaps we should discuss this with upstream Ghidra devs to hear their input. the above sounds like it should work and probably won't often be broken; therefore, can we rely on it? can it be documented as part of Ghidra's behavior?

i dont think its really bad if its not documented yet still works - its just something we need to remember and document internally, in case things break later on.

**Comment by williballenthin** [comment]
here's a link to the implementation of extension installation, and its just as you said:

https://github.com/NationalSecurityAgency/ghidra/blob/9ec89c37fb30d6228ed82d4cf1441b7a7aa0a3f1/Ghidra/Framework/Project/src/main/java/ghidra/framework/plugintool/dialog/ExtensionUtils.java#L788-L801

**Comment by rchtsang** [comment]
I've found extracting to `$GHIDRA_INSTALL_DIR/Ghidra/Extensions` also works.

**Comment by rchtsang** [comment]
I'm not quite sure. I went through the full installation process once a while back, and after upgrading to Ghidra 10.3 tried to do it again. I did open the GUI after that, but found that I didn't need to set anything else up. I can try this again and see if headless mode works without opening the GUI though.

**Comment by Ruturaj4** [comment]
> > I've found extracting to `$GHIDRA_INSTALL_DIR/Ghidra/Extensions` also works.
> 
> @rchtsang did you find that you could use Ghidrathon in Ghidra headless mode w/out first configuring the extension via Ghidra's UI?

Also, in that case, what about disabling the jython support, should that work fine? I don't have an access to the GUI at all.

**Comment by rchtsang** [comment]
That I’m not sure about, it’s possible there are some locally stored
configurations that I’m unaware of, but I removed ~/.ghidra on uninstall
and ghidrathon still worked on reinstall, so if there’s anything beyond
that I should be removing for fresh install let me know and I can try it.

**Comment by Ruturaj4** [comment]
Btw, I just tested that with my script and it works fine! Thanks for the great project!

**Comment by larchchen** [comment]
> I've found extracting to `$GHIDRA_INSTALL_DIR/Ghidra/Extensions` also works.

Apparently the difference between `$GHIDRA_INSTALL_DIR/Extensions` and `$GHIDRA_INSTALL_DIR/Ghidra/Extensions` matters here. The [official document](https://github.com/NationalSecurityAgency/ghidra/blob/d7d6b44e296ac4a215766916d5c24e8b53b2909a/GhidraDocs/InstallationGuide.html#L427) refers to the later on. 

The  `<GhidraInstallDir>/Extensions` are "by default uninstalled" according to the same manual a few lines above.

**Comment by mike-hunhoff** [comment]
Thanks all - I've update Ghidrathon's README to specify unzip to `$GHIDRA_INSTALL_DIR/Ghidra/Extensions` as the preferred method for installing Ghidrathon w/out using Ghidra's UI.
