### ISSUE TITLE
make installation easier

### ISSUE THREAD

**Issue by williballenthin** [mandiant/Ghidrathon#49]
Despite being familiar with Ghidrathon development, there have been times that I've avoided using Ghidrathon because its a pain to install. When I visit a project and see that I have to compile software from source I am much less likely to experiment with it (probably due to past experiences when the compilation failed, and I'm stuck debugging the build process).

We should investigate how to make Ghidrathon easier to setup and use.

In a perfect world, I think I'd want to see: users download a single file from GH releases page, put it in a specific directory, and everything just works. How close can we get to this ideal?

**Comment by williballenthin** [comment]
In both the above scenarios, it would be nice if Ghidrathon prompted the user for the python path (autodetect system python or activated virtualenv, enable overriding with a virtualenv) during installation. This way users can be very explicit about where they want to load python from and where JEP should be installed.

**Comment by rchtsang** [comment]
> Alternatively, we could ask users to install JEP via pip and Ghidrathon searches for the resulting jep.dll in the python path. However, JEP doesn't distribute pre-built jep.dll files (nor wheels, today), so this would still require users to have a few additional dependencies (C/C++ compiler).

From my understanding, this is the default behavior already no? `build.gradle` appears to pip install jep to the current python environment and `configure_jep_native_binaries.py` copies the corresponding jep binary to the `ghidrathon/os/<arch>` directory for build.

**Comment by williballenthin** [comment]
yes, you're right, but my point is that asking users to do a gradle build is not ideal. i'm proposing that users download a prebuilt .zip of ghidrathon and put it directly in their Extensions directory. in this scenario, the extension doesn't get unpacked/repacked to include the dll.

**Comment by mike-hunhoff** [comment]
This should be addressed in https://github.com/mandiant/Ghidrathon/commit/32f3969e09a5d29197cabbc28d93dc9c572d7e45 - please reopen if you continue to have issues after this is released.
