### ISSUE TITLE
If interactive interpreter of Ghidrathon can be used in other text editor or IDEs. 

### ISSUE THREAD

**Issue by anzosasuke** [mandiant/Ghidrathon#56]
I would like to know if the Ghidrathon Python interpreter can be used in Pycharm or other IDEs. I find it very difficult to use the interpreter in the GUI.

**Comment by mike-hunhoff** [comment]
@anzosasuke thank you for your suggestion.  We have not explicitly tested or added support for IDE development but it’s on our radar along with adding autocomplete to Ghidrathon’s interpreter to improve the overall experience. Is there anything specific you would like to see improved in the interpreter that would improve your experience?

**Comment by anzosasuke** [comment]
auto complete, indentation, output display somethings like that could be helpful. Thanks.
