### ISSUE TITLE
Ensure sys.executable set correctly

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/Ghidrathon#62]
@Forsworns oh this is an interesting one. Based on the output that you provided I tracked the offending lines of code to `packaging.types`: https://github.com/pypa/packaging/blob/3030822b0b06a43fbbb2710da7b0846d1bebd2ba/src/packaging/tags.py#L399-L410

The code calls `subprocess.run` where the target executable is pulled from `sys.executable`. `sys.executable` is set correctly in my Linux test environment:
```python
>>> import sys
>>> sys.executable
'/home/spring/dragon/.env/bin/python3`
```

Can you run the code listed above from your Ghidrathon interpreter? I'm guessing `sys.executable` is set to the `Java` executable used to run Ghidra in your Mac environment...

_Originally posted by @mike-hunhoff in https://github.com/mandiant/Ghidrathon/issues/59#issuecomment-1660841345_

**Comment by mike-hunhoff** [comment]
It appears the `Jep` developers know of this issue: https://github.com/ninia/jep/blob/056ce9907f5ecbf2364df1ec55755404b2e8a947/commands/test.py#L73-L76 which they avoid by setting the environment variable [PYTHONEXECUTABLE](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONEXECUTABLE). Ghidrathon probably needs to set this as well...or manually configure `sys.executable` during the init phase if running in a Mac environment. Let's open a new issue to track this work

_Originally posted by @mike-hunhoff in https://github.com/mandiant/Ghidrathon/issues/59#issuecomment-1660865331_

**Comment by Forsworns** [comment]
Yes, it is set to the Java executable

![image](https://github.com/mandiant/Ghidrathon/assets/24567080/482a6608-18f3-479c-9090-e6c6107d4b48)

I think an optional configurable item in `GhidrathonConfig.xml` will be helpful. I manually revise it to my python executable and now it works well :cat:

![image](https://github.com/mandiant/Ghidrathon/assets/24567080/4a7a7839-8242-4ab3-9553-66ad2a878522)

**Comment by Forsworns** [comment]
I'll try to resolve the issue later this evening (my time zone), but  at the moment I must depart for work :(

**Comment by mike-hunhoff** [comment]
This also appears to be an issue on Windows systems.

**Comment by mike-hunhoff** [comment]
This should be addressed in https://github.com/mandiant/Ghidrathon/commit/32f3969e09a5d29197cabbc28d93dc9c572d7e45 - please reopen if you continue to have issues after this is released.
