### ISSUE TITLE
clearListing Exception

### ISSUE THREAD

**Issue by 0xling** [mandiant/Ghidrathon#65]
I use `clearListing` API will raise an Exception, but it work normal in jpython

```
>> clearListing(toAddr(0))
Traceback (most recent call last):
  File "ghidra_10.3.1_PUBLIC/Ghidra/Extensions/Ghidrathon-2.2.1/data/python/jepeval.py", line 66, in jepeval
    more_input_needed = _jepeval(line)
  File "ghidra_10.3.1_PUBLIC/Ghidra/Extensions/Ghidrathon-2.2.1/data/python/jepeval.py", line 49, in _jepeval
    exec(compile(line, "<string>", "single"), globals(), globals())
  File "<string>", line 1, in <module>
RuntimeError: ghidra.framework.model.DomainObjectException caused by: ghidra.util.exception.ClosedException: File is closed
```

**Comment by mike-hunhoff** [comment]
Thank you for reporting @0xling . Can you please provide more details including:
- Ghidra version
- Ghidrathon version
- Jep version
- OS version

**Comment by 0xling** [comment]
```
ghidra: 10.3.1
Ghidrathon version: 2.2.1
jep:  4.1.1
os: Ubuntu 22.04.1 LTS
```

the test binary need to be arm architecture.  I upload mine binary.
 [hello.zip](https://github.com/mandiant/Ghidrathon/files/12307659/hello.zip)

open Ghidrathon, and run `clearListing(toAddr(0x10520))`

**Comment by 0xling** [comment]
disassemble will error at every time including the first time.

Ghidra to open hello.arm binary, and clear code bytes at address 0x10520, and run ` disassemble(toAddr(0x10520))`

```
>>> disassemble(toAddr(0x10520))
Traceback (most recent call last):
  File "Extensions/Ghidrathon-2.2.1-v2/data/python/jepeval.py", line 66, in jepeval
    more_input_needed = _jepeval(line)
  File "Extensions/Ghidrathon-2.2.1-v2/data/python/jepeval.py", line 49, in _jepeval
    exec(compile(line, "<string>", "single"), globals(), globals())
  File "<string>", line 1, in <module>
RuntimeError: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Program.getLanguageID()" because "program" is null

```

**Comment by mike-hunhoff** [comment]
Again, thank you for the thorough report. Your first bug appears to be a result of switching Ghidrathon to use Jep `SharedInterpreter`s in Ghidrathon `2.2.0` - I have not had a chance to triage your second bug to determine if it is also related. Unfortunately I do not have a quick fix and I won't have time to fully triage and propose a fix until next week. In the mean time, please use [this previous Ghidrathon](https://github.com/mandiant/Ghidrathon/releases/tag/v2.1.0) release.

**Comment by mike-hunhoff** [comment]
@0xling this bug is fixed in our latest release: https://github.com/mandiant/Ghidrathon/releases/tag/v3.0.0.
