### ISSUE TITLE
expose current `GhidraScript` instance to Python

### ISSUE THREAD

**Issue by slippycheeze** [mandiant/Ghidrathon#79]
[`ghidra.util.Msg`][Msg] has some useful "popup" functions that I wanted to use, specifically the ones that take a Java `Throwable` for displaying Java exception details; for example:

```java
public static void showError​(java.lang.Object originator, java.awt.Component parent, java.lang.String title, java.lang.Object message)
```

That first argument, `originator`, is supposed to be the Java thing that is displaying the message; typical use would be `Msg.showError(this, ...)` in Java.  I'd like to do the same in Ghidrathon, but there is no easy way I can see to access the current `GhidraScript` derivative.

I can get the current script by calling [`jepwrappers.get_script()`][get_script], which returns the `ghidrathon.GhidrathonScript` instance, if I want, but it isn't exposed any other way that I can see.

I'd suggest adding `getCurrentScript()` or something very similar as a "public" version of that to the globals of the python script environment?

[Msg]: https://ghidra.re/ghidra_docs/api/ghidra/util/Msg.html
[get_script]: https://github.com/mandiant/Ghidrathon/blob/748983133e5290f8fed74977ad69422926d78a1f/data/python/jepwrappers.py#L52C8-L52C8

**Comment by mike-hunhoff** [comment]
@slippycheeze thank you for the suggestion. I like the idea of adding a new Python function, named `getCurrentScript`, to the Python builtins scope. Alternatively, we should consider adding `script` the Python builtins scope to better align with the way Ghidrathon exposes other `GhidraScript` variables like `currentProgram` and `monitor`.
