### ISSUE TITLE
Ghidraton not displayed in window tab

### ISSUE THREAD

**Issue by Voxanimus** [mandiant/Ghidrathon#93]
I installed Ghidraton and all the dependencies.
I followed the instalation guidelines.
Ghidraton is in the extension folder of Ghidra but Ghidraton is not displayed in thw window tab.
There is no error in the log file but no information on Ghidraton either.
Any advice on how I can fix this ?

System information:
OS: Arch Linux x86_64
Kernel version: 6.7.3-arch-1
Jep version: 4.2.0
Java: java-17-openjdk, version 17.0.10
Ghidraton: 4.0.0
Python: 3.11.6
Ghidra: 11.0.1

**Comment by mike-hunhoff** [comment]
Hi @Voxanimus thank you for reaching out! Ghidra _should_ prompt you to configure the extension but sometimes it does not. You can manually configure the Ghidrathon extension from Ghidra's CodeBrowser window by navigating to `File > Configure`, selecting `Configure` under `Ghidra Core`, and selecting the checkbox next to `GhidrathonPlugin` (you can use the `Filter` box to search for `GhidrathonPlugin`). Ghidrathon will be listed under the CodeBrowser's `Window` tab after selecting `Ok`.

If you don't find `GhidrathonPlugin` listed under `Ghidra Core` then double-check that you have _unzipped_ the Ghidrathon extension (`.zip`) to the directory `<absolute_path_to_ghidra_install_dir>\Ghidra\Extensions`. The Ghidrathon extension is the `.zip` included in the release `.zip`.

**Comment by mike-hunhoff** [comment]
Hi @Voxanimus - were my suggestions able to solve this issue for you?

**Comment by mike-hunhoff** [comment]
No problem, thank you for responding. I'll close this for now - please reopen if have a change to try and continue to experience problems.

**Comment by yodaxtah** [comment]
I also had this problem, but didn't find any reference to what was going on. I found people describing error messages, but I wasn't sure where I should find them. Since I had none, I wasn't seeing anything.

I only found this issue accidentally by searching for what the installation path should be. Therefore, I suggest someone to add this to the README. For me, it seems to have worked.
