### ISSUE TITLE
Ghidrathon menu don't appear in Windows menu

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/Ghidrathon#96]
I just tried Ghidrathon for the first time.
The Ghidrathon menu item does not appear on the Window menu of Ghidra CodeBrowser
But Python 3 in Script Manager does and executes script giadrathon_example.py successfully
My OS: Windows 10
Ghidra 11.0.1
Ghidrathon 4.0

I didn't find out why.
Does Ghidrathon have any flags to output debug log?
Brgds

**Comment by mike-hunhoff** [comment]
Hi @HongThatCong - thanks for reaching out. Please make sure you've configured Ghidrathon by navigating in Ghidra's CodeBrowser window to `File > Configure`, selecting `Configure` under `Ghidra Core`, and selecting the checkbox next to `GhidrathonPlugin` (you can use the `Filter` box to search for `GhidrathonPlugin`). Ghidrathon will be listed under the CodeBrowser's `Window` tab after selecting `Ok`.

Ghidrathon by default is configured to output logs to Ghidra's `application.log` file (`<home_directory>\.ghidra\.ghidra_<version>\application.log`).

**Comment by HongThatCong** [comment]
I read the instructions wrong. I did not enable Ghidrathon in Code Browser Windows - File - Configure menu
Everything was fine. Ghidrathon has appeared in the Windows menu of the Code Browser window.
Thank you very much
