### ISSUE TITLE
enable users to configure, via an environment variable, the path where the file ghidrathon.save is written

### ISSUE THREAD

**Issue by checooh** [mandiant/Ghidrathon#98]
Hello!

I'm using Ghidra on NixOS. NixOS is a Linux distribution that is different from more traditional Linux distributions in such a way that the installed packages are stored in the read-only mountpoint, so it's impossible just to place the ghidrathon.save file into the lib/ghidra subdirectory of Ghidra installation directory. 
I was able to cope by running "python ghidrathon_configure ." to create the ghidrathon.save file in my home and then adding an override to my NixOS configuration:

```nix
nixpkgs.overlays = let
    ghidrathon_save_file = pkgs.writeText "ghidrathon.save" ''
      <contents of ghidrathon.save go here>
    '';
  in [ (self: super: {
    ghidra = super.ghidra.overrideAttrs (old:{
      postFixup = ''
        ln -s ${ghidrathon_save_file} $out/lib/ghidra/ghidrathon.save
      '' + old.postFixup;
    });
  }) ];
```

While this solution does help, and allows running Ghidrathon, it is kind of a hack, and it'd be really nice to have a way to configure the ghidrathon.save file location. For example, it could be configured through a system environment variable, named something like GHIDRATHON_SAVE_PATH. 

Can you guys please add a feature like that?

**Comment by mike-hunhoff** [comment]
Thank you for reporting @checooh . This is a very reasonable change that we can add in a future release.
